-- 3.1 Data Profiling

USE ROLE TPCH_DEVELOPER;
USE SCHEMA TPCH_ANALYTICS_DB.STAGING;

SELECT 
    N.N_NAME AS COUNTRY,
    COUNT(DISTINCT C.C_CUSTKEY) AS CUSTOMER_COUNT
FROM CUSTOMER C
JOIN NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
GROUP BY N.N_NAME
ORDER BY CUSTOMER_COUNT DESC;


SELECT O_ORDERSTATUS_DESC, COUNT(DISTINCT O_ORDERKEY)
FROM ANALYTICS.ORDERS_SILVER
GROUP BY 1;


SELECT L_PART_TYPE, COUNT(DISTINCT L_ORDERKEY)
FROM ANALYTICS.LINEITEM_SILVER
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;


-- 3.2 Explain

EXPLAIN

SELECT 
    O_ORDER_YEAR,
    O_ORDER_MONTH,
    O_ORDERSTATUS_DESC,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(O_TOTALPRICE) AS TOTAL_REVENUE,
    AVG(O_TOTALPRICE) AS AVG_ORDER_VALUE,
    COUNT(DISTINCT O_CUSTKEY) AS UNIQUE_CUSTOMERS
FROM ANALYTICS.ORDERS_SILVER
WHERE O_ORDERDATE >= DATE '1995-01-01'
GROUP BY 1, 2, 3
ORDER BY 1, 2;

