ALTER ACCOUNT SET TIMEZONE = 'Asia/Ho_Chi_Minh';
SHOW PARAMETERS LIKE 'TIMEZONE';


USE ROLE USERADMIN;

/*
TPCH_ADMIN;
TPCH_DEVELOPER; -- Developer: load data, transform
TPCH_ANALYST; -- Analyst: query, report
TPCH_VIEWER; -- Viewer: only view reports
*/

CREATE ROLE TPCH_ADMIN;
CREATE ROLE TPCH_DEVELOPER;
CREATE ROLE TPCH_ANALYST;
CREATE ROLE TPCH_VIEWER;

-- setup role hỉerarchy
/*
Naive Rule:
TPCH_ADMIN inherits all perms of TPCH_DEVELOPER, TPCH_DEVELOPER inherits all perms of TPCH_ANALYST, etc
*/

GRANT ROLE TPCH_VIEWER TO ROLE TPCH_ANALYST;
GRANT ROLE TPCH_ANALYST TO ROLE TPCH_DEVELOPER;
GRANT ROLE TPCH_DEVELOPER TO ROLE TPCH_ADMIN;
GRANT ROLE TPCH_ADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE DATABASE TPCH_ANALYTICS_DB;
USE DATABASE TPCH_ANALYTICS_DB;
CREATE SCHEMA STAGING;
CREATE SCHEMA ANALYTICS;
CREATE SCHEMA REPORTS;
CREATE SCHEMA UDFS;
CREATE SCHEMA CONTROL;

GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_VIEWER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_VIEWER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_VIEWER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_VIEWER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.CONTROL TO ROLE TPCH_ANALYST;


-- A. TPCH_VIEWER: View Reports
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;


-- B. TPCH_ANALYST: inherit from TPCH_VIEWER + new perms (create view)
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;

GRANT CREATE VIEW ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT CREATE VIEW ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;

-- C. TPCH_DEVELOPER: inherit from TPCH_ANALYST + new perms (DDL/DML + control task/function)
GRANT CREATE STAGE, CREATE VIEW ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;

GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_DEVELOPER;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_DEVELOPER;


GRANT CREATE TABLE, CREATE PROCEDURE, CREATE TASK ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER;
GRANT CREATE TABLE, CREATE PROCEDURE, CREATE TASK ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_DEVELOPER;
GRANT CREATE TABLE, CREATE PROCEDURE, CREATE TASK ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER;
GRANT CREATE TABLE, CREATE PROCEDURE, CREATE TASK ON SCHEMA TPCH_ANALYTICS_DB.CONTROL TO ROLE TPCH_DEVELOPER;
GRANT CREATE FUNCTION, CREATE PIPE, CREATE TABLE, CREATE STREAM ON SCHEMA TPCH_ANALYTICS_DB.CONTROL TO ROLE TPCH_DEVELOPER;
GRANT OPERATE ON ALL TASKS IN SCHEMA TPCH_ANALYTICS_DB.CONTROL TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA TPCH_ANALYTICS_DB.CONTROL TO ROLE TPCH_DEVELOPER;
GRANT SELECT ON ALL STREAMS IN SCHEMA TPCH_ANALYTICS_DB.CONTROL TO ROLE TPCH_DEVELOPER;

GRANT OPERATE ON FUTURE TASKS IN SCHEMA TPCH_ANALYTICS_DB.CONTROL TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA TPCH_ANALYTICS_DB.CONTROL TO ROLE TPCH_DEVELOPER;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA TPCH_ANALYTICS_DB.CONTROL TO ROLE TPCH_DEVELOPER;


GRANT CREATE FUNCTION ON SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA TPCH_ANALYTICS_DB.UDFS TO ROLE TPCH_DEVELOPER;


-- role check
SHOW GRANTS OF ROLE TPCH_VIEWER;
SHOW GRANTS TO ROLE TPCH_ANALYST;
SHOW GRANTS TO ROLE TPCH_DEVELOPER;
SHOW GRANTS TO ROLE TPCH_ADMIN;
SHOW GRANTS ON DATABASE TPCH_ANALYTICS_DB;


-- Granting a Role to a User
GRANT ROLE <role_name> TO USER <user_name>;