/*
In this case study, I chose to create a pipe by batch (not streaming) (because I am testing by reading from the internal stage, and need to configure cloud service if using streaming)
See setup streaming https://docs.snowflake.com/en/sql-reference/sql/create-pipe
*/


USE ROLE TPCH_DEVELOPER;

ALTER TABLE TPCH_ANALYTICS_DB.STAGING.ORDERS ADD COLUMN FROM_SOURCE VARCHAR;
ALTER TABLE TPCH_ANALYTICS_DB.STAGING.ORDERS ADD COLUMN CREATED_AT TIMESTAMP_LTZ;

ALTER TABLE TPCH_ANALYTICS_DB.STAGING.LINEITEM ADD COLUMN FROM_SOURCE VARCHAR;
ALTER TABLE TPCH_ANALYTICS_DB.STAGING.LINEITEM ADD COLUMN CREATED_AT TIMESTAMP_LTZ;

ALTER TABLE TPCH_ANALYTICS_DB.STAGING.CUSTOMER ADD COLUMN FROM_SOURCE VARCHAR;
ALTER TABLE TPCH_ANALYTICS_DB.STAGING.CUSTOMER ADD COLUMN CREATED_AT TIMESTAMP_LTZ;

ALTER TABLE TPCH_ANALYTICS_DB.STAGING.NATION ADD COLUMN FROM_SOURCE VARCHAR;
ALTER TABLE TPCH_ANALYTICS_DB.STAGING.NATION ADD COLUMN CREATED_AT TIMESTAMP_LTZ;

ALTER TABLE TPCH_ANALYTICS_DB.STAGING.PART ADD COLUMN FROM_SOURCE VARCHAR;
ALTER TABLE TPCH_ANALYTICS_DB.STAGING.PART ADD COLUMN CREATED_AT TIMESTAMP_LTZ;

ALTER TABLE TPCH_ANALYTICS_DB.STAGING.PARTSUPP ADD COLUMN FROM_SOURCE VARCHAR;
ALTER TABLE TPCH_ANALYTICS_DB.STAGING.PARTSUPP ADD COLUMN CREATED_AT TIMESTAMP_LTZ;

ALTER TABLE TPCH_ANALYTICS_DB.STAGING.REGION ADD COLUMN FROM_SOURCE VARCHAR;
ALTER TABLE TPCH_ANALYTICS_DB.STAGING.REGION ADD COLUMN CREATED_AT TIMESTAMP_LTZ;

ALTER TABLE TPCH_ANALYTICS_DB.STAGING.SUPPLIER ADD COLUMN FROM_SOURCE VARCHAR;
ALTER TABLE TPCH_ANALYTICS_DB.STAGING.SUPPLIER ADD COLUMN CREATED_AT TIMESTAMP_LTZ;


-- ============================================================================
-- ## Create Pipe
-- ============================================================================



USE DATABASE TPCH_ANALYTICS_DB;

CREATE OR REPLACE PIPE CONTROL.PIPE_LOAD_ORDERS
AUTO_INGEST = FALSE -- Automate the data ingestion process (Choose TRUE)
AS
COPY INTO STAGING.ORDERS (
    O_ORDERKEY,
    O_CUSTKEY,
    O_ORDERSTATUS,
    O_TOTALPRICE,
    O_ORDERDATE,
    O_ORDERPRIORITY,
    O_CLERK,
    O_SHIPPRIORITY,
    O_COMMENT,
    FROM_SOURCE,
    CREATED_AT
)
FROM (
    SELECT 
        $1::NUMBER(38,0),
        $2::NUMBER(38,0),
        $3::VARCHAR(1),
        $4::NUMBER(15,2),
        $5::DATE,
        $6::VARCHAR(15),
        $7::VARCHAR(15),
        $8::NUMBER(38,0),
        $9::VARCHAR(79),
        METADATA$FILENAME::VARCHAR,
        METADATA$FILE_LAST_MODIFIED
        -- METADATA$START_SCAN_TIME
    
    FROM @STAGING.TPCH_DATA_STAGE
)
PATTERN='.*tpch_sf1_orders_.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
);


CREATE OR REPLACE PIPE CONTROL.PIPE_LOAD_LINEITEM
AUTO_INGEST = FALSE
AS
COPY INTO STAGING.LINEITEM (
    L_ORDERKEY,
    L_PARTKEY,
    L_SUPPKEY,
    L_LINENUMBER,
    L_QUANTITY,
    L_EXTENDEDPRICE,
    L_DISCOUNT,
    L_TAX,
    L_RETURNFLAG,
    L_LINESTATUS,
    L_SHIPDATE,
    L_COMMITDATE,
    L_RECEIPTDATE,
    L_SHIPINSTRUCT,
    L_SHIPMODE,
    L_COMMENT,
    FROM_SOURCE,
    CREATED_AT
)
FROM (
    SELECT 
        $1::NUMBER(38,0),
        $2::NUMBER(38,0),
        $3::NUMBER(38,0),
        $4::NUMBER(38,0),
        $5::NUMBER(12,2),
        $6::NUMBER(12,2),
        $7::NUMBER(12,2),
        $8::NUMBER(12,2),
        $9::VARCHAR(1),
        $10::VARCHAR(1),
        $11::DATE,
        $12::DATE,
        $13::DATE,
        $14::VARCHAR(25),
        $15::VARCHAR(10),
        $16::VARCHAR(44),
        METADATA$FILENAME::VARCHAR,
        METADATA$FILE_LAST_MODIFIED
    
    FROM @STAGING.TPCH_DATA_STAGE
)
PATTERN='.*tpch_sf1_line_item_.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
);


--

CREATE OR REPLACE PIPE CONTROL.PIPE_LOAD_CUSTOMER
AUTO_INGEST = FALSE
AS
COPY INTO STAGING.CUSTOMER (
    C_CUSTKEY,
    C_NAME,
    C_ADDRESS,
    C_NATIONKEY,
    C_PHONE,
    C_ACCTBAL,
    C_MKTSEGMENT,
    C_COMMENT,

    FROM_SOURCE,
    CREATED_AT
)
FROM (
    SELECT 
        $1::NUMBER(38,0),
        $2::VARCHAR(25),
        $3::VARCHAR(40),
        $4::NUMBER(38,0),
        $5::VARCHAR(15),
        $6::NUMBER(12,2),
        $7::VARCHAR(10),
        $8::VARCHAR(117),

        METADATA$FILENAME::VARCHAR,
        METADATA$FILE_LAST_MODIFIED
    
    FROM @STAGING.TPCH_DATA_STAGE
)
PATTERN='.*tpch_sf1_customer_.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
);


--

CREATE OR REPLACE PIPE CONTROL.PIPE_LOAD_NATION
AUTO_INGEST = FALSE
AS
COPY INTO STAGING.NATION (
    N_NATIONKEY,
    N_NAME,
    N_REGIONKEY,
    N_COMMENT,
    FROM_SOURCE,
    CREATED_AT
)
FROM (
    SELECT 
        $1::NUMBER(38,0),
        $2::VARCHAR(25),
        $3::NUMBER(38,0),
        $4::VARCHAR(152),
        METADATA$FILENAME::VARCHAR,
        METADATA$FILE_LAST_MODIFIED
    
    FROM @STAGING.TPCH_DATA_STAGE
)
PATTERN='.*tpch_sf1_nation_.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
);

--

CREATE OR REPLACE PIPE CONTROL.PIPE_LOAD_PART
AUTO_INGEST = FALSE
AS
COPY INTO STAGING.PART (
    P_PARTKEY,
    P_NAME,
    P_MFGR,
    P_BRAND,
    P_TYPE,
    P_SIZE,
    P_CONTAINER,
    P_RETAILPRICE,
    P_COMMENT,

    FROM_SOURCE,
    CREATED_AT
)
FROM (
    SELECT 
        $1::NUMBER(38,0),
        $2::VARCHAR(55),
        $3::VARCHAR(25),
        $4::VARCHAR(10),
        $5::VARCHAR(25),
        $6::NUMBER(38,0),
        $7::VARCHAR(10),
        $8::NUMBER(12,2),
        $9::VARCHAR(23),

        METADATA$FILENAME::VARCHAR,
        METADATA$FILE_LAST_MODIFIED
    
    FROM @STAGING.TPCH_DATA_STAGE
)
PATTERN='.*tpch_sf1_part_.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
);

--

CREATE OR REPLACE PIPE CONTROL.PIPE_LOAD_PARTSUPP
AUTO_INGEST = FALSE
AS
COPY INTO STAGING.PARTSUPP (
    PS_PARTKEY,
    PS_SUPPKEY,
    PS_AVAILQTY,
    PS_SUPPLYCOST,
    PS_COMMENT,
    FROM_SOURCE,
    CREATED_AT
)
FROM (
    SELECT 
        $1::NUMBER(38,0),
        $2::NUMBER(38,0),
        $3::NUMBER(38,0),
        $4::NUMBER(12,2),
        $5::VARCHAR(199),
        METADATA$FILENAME::VARCHAR,
        METADATA$FILE_LAST_MODIFIED
    
    FROM @STAGING.TPCH_DATA_STAGE
)
PATTERN='.*tpch_sf1_partsupp_.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
);

--

CREATE OR REPLACE PIPE CONTROL.PIPE_LOAD_REGION
AUTO_INGEST = FALSE
AS
COPY INTO STAGING.REGION (
    R_REGIONKEY,
    R_NAME,
    R_COMMENT,
    FROM_SOURCE,
    CREATED_AT
)
FROM (
    SELECT 
        $1::NUMBER(38,0),
        $2::VARCHAR(25),
        $3::VARCHAR(152),
        METADATA$FILENAME::VARCHAR,
        METADATA$FILE_LAST_MODIFIED
    
    FROM @STAGING.TPCH_DATA_STAGE
)
PATTERN='.*tpch_sf1_region_.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
);


--

CREATE OR REPLACE PIPE CONTROL.PIPE_LOAD_SUPPLIER
AUTO_INGEST = FALSE
AS
COPY INTO STAGING.SUPPLIER (
    S_SUPPKEY,
    S_NAME,
    S_ADDRESS,
    S_NATIONKEY,
    S_PHONE,
    S_ACCTBAL,
    S_COMMENT,

    FROM_SOURCE,
    CREATED_AT
)
FROM (
    SELECT 
        $1::NUMBER(38,0),
        $2::VARCHAR(25),
        $3::VARCHAR(40),
        $4::NUMBER(38,0),
        $5::VARCHAR(15),
        $6::NUMBER(12,2),
        $7::VARCHAR(101),
        METADATA$FILENAME::VARCHAR,
        METADATA$FILE_LAST_MODIFIED
    
    FROM @STAGING.TPCH_DATA_STAGE
)
PATTERN='.*tpch_sf1_supplier_.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
);


-- ============================================================================
-- ## Set Job
-- ============================================================================
-- use compute serverless
CREATE OR REPLACE TASK TPCH_ANALYTICS_DB.CONTROL.TASK_REFRESH_PIPE
  SCHEDULE = 'USING CRON 05 00 * * * Asia/Ho_Chi_Minh'
  AS
    BEGIN
        ALTER PIPE TPCH_ANALYTICS_DB.CONTROL.PIPE_LOAD_LINEITEM REFRESH;
        ALTER PIPE TPCH_ANALYTICS_DB.CONTROL.PIPE_LOAD_CUSTOMER REFRESH;
        ALTER PIPE TPCH_ANALYTICS_DB.CONTROL.PIPE_LOAD_NATION REFRESH;
        ALTER PIPE TPCH_ANALYTICS_DB.CONTROL.PIPE_LOAD_ORDERS REFRESH;
        ALTER PIPE TPCH_ANALYTICS_DB.CONTROL.PIPE_LOAD_PART REFRESH;
        ALTER PIPE TPCH_ANALYTICS_DB.CONTROL.PIPE_LOAD_PARTSUPP REFRESH;
        ALTER PIPE TPCH_ANALYTICS_DB.CONTROL.PIPE_LOAD_REGION REFRESH;
        ALTER PIPE TPCH_ANALYTICS_DB.CONTROL.PIPE_LOAD_SUPPLIER REFRESH;
    END;

-- trigger task
ALTER TASK TPCH_ANALYTICS_DB.CONTROL.TASK_REFRESH_PIPE RESUME;

-- suspend
-- ALTER TASK TPCH_ANALYTICS_DB.CONTROL.TASK_REFRESH_PIPE SUSPEND;